language: ruby

before_script:
  - psql -c 'create database minidusen_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS minidusen_test;'

script: bundle exec rspec spec

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de

matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.5.0.mysql2
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.5.0.pg
